"""Add location hierarchy

Revision ID: bd016fba3126
Revises: e62ad0be466b
Create Date: 2026-09-29 11:44:59.061026+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'bd016fba3126'
down_revision: Union[str, None] = 'e62ad0be466b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('location_type', sa.String(length=64), server_default='poi', nullable=False))
    op.add_column('locations', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_locations_location_type'), 'locations', ['location_type'], unique=False)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'locations', 'locations', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_type'), table_name='locations')
    op.drop_column('locations', 'parent_id')
    op.drop_column('locations', 'location_type')
    # ### end Alembic commands ###
