"""Add missing location indexes

Revision ID: f8f11c33ff67
Revises: bd016fba3126
Create Date: 2026-09-29 11:55:45.074996+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'f8f11c33ff67'
down_revision: Union[str, None] = 'bd016fba3126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_locations_category'), 'locations', ['category'], unique=False)
    op.create_index(op.f('ix_locations_district'), 'locations', ['district'], unique=False)
    op.create_index(op.f('ix_locations_state'), 'locations', ['state'], unique=False)
    op.create_index(op.f('ix_locations_union_territory'), 'locations', ['union_territory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_union_territory'), table_name='locations')
    op.drop_index(op.f('ix_locations_state'), table_name='locations')
    op.drop_index(op.f('ix_locations_district'), table_name='locations')
    op.drop_index(op.f('ix_locations_category'), table_name='locations')
    # ### end Alembic commands ###
